function [opt,fval, exitflag, output]=SOMP_Doppler( SAT,...
                                                    SAT_V,...                                          
                                                    Doppler_measure,...
                                                    opt,...
                                                    h0,...
                                                    tolx,...
                                                    tolf,...
                                                    maxiter,...
                                                    maxfun,...
                                                    freqDownLink)
                                       
% Функция находит решение CОМП Пост по измерения частоты Доплера вниз 
% (см. функцию dopplerSAT1_downLink)                                       
% 
% var@mail.spbstu.ru, V.A. Vargauzin, декабрь 2020

 if  isempty(SAT) || isempty(Doppler_measure)
     opt=[nan nan];
     fval=nan;
     output=nan;
     exitflag=0;     
     return
 end
 
 if nargin < 10
     freqDownLink=0;
 end
 
          % управление печатью во время алгоритма поиска минимума:
           printtype='none'; % 'none' 'iter' 'final' 'simplex'             
                                          
           % Вычисление min квадратичного функционала невязки
%            [opt,fval, exitflag, output]=fminsearchVARG(@fun, opt,...
%                                                  optimset('TolFun',tolf,...
%                                                           'TolX',  tolx,...
%                                                           'MaxFunEvals',maxfun,...
%                                                           'MaxIter',maxiter,...
%                                                           'Display', printtype ));
           [opt,fval, exitflag, output]=fminsearch(@fun, opt,...
                                                 optimset('TolFun',tolf,...
                                                          'TolX',  tolx,...
                                                          'MaxFunEvals',maxfun,...
                                                          'MaxIter',maxiter,...
                                                          'Display', printtype ));

            % функция fminsearchVARG - версия функции MATLAB fminsearch, из которой
            % удалено большинство сервисных опций и оставлена в основном лишь
            % математика
            % +
            % 1) добавлены комментарии
            % 2) модифицирован критерий останова алгоритма поиска минимума

                       function dR=fun(opt)

                             [x, y, z]=llh2xyz( opt(1), opt(2), h0 ); % декартовы координаты 
                             hipoteza= [x y z]';
                             
                             if freqDownLink==0
%                              freqDownLink=0; % несущая равна нулю, посколку в качестве измерения 
%                               % используется не частота Доплера, а линейно с ней связанная радиальная
%                               % скорость
                             [ ~,Doppler_hipoteza]=dopplerSAT1_downLink(SAT,...
                                                                        SAT_V,...
                                                                        hipoteza,...
                                                                        freqDownLink);  
                             else
                             [ Doppler_hipoteza]=dopplerSAT1_downLink(SAT,...
                                                                        SAT_V,...
                                                                        hipoteza,...
                                                                        freqDownLink); 
                             end
                             d=Doppler_hipoteza-Doppler_measure; % вектор-столбец невязки                             
                             dR=nansum(d.^2);
                             %dR=(nansum(d))^2;

                       end   
                     
end